-- ==============================================================
-- SCHEMA_DRIFT.sql — DDL restante entre migrations e schema vivo
-- Projeto: doufsxqlfjyuvxuezpln
-- Gerado em: 2026-09-16 (tentativa)
-- Fonte: supabase db diff --linked --schema public
-- ==============================================================
--
-- NÃO FOI POSSÍVEL CALCULAR — e não é um problema de credencial.
--
-- `supabase db diff` reconstrói o schema do zero em um shadow database,
-- reaplicando as ~2.988 migrations de supabase/migrations/ em ordem, para
-- só então comparar com o schema vivo. Esse replay trava antes de chegar
-- à comparação porque uma parte real (e provavelmente extensa) do schema
-- vivo foi construída fora do fluxo de migrations ao longo de meses
-- (dashboard/MCP/scripts pontuais), sem representação em nenhum arquivo.
--
-- Confirmado ao vivo em 2026-09-16, na primeira execução do
-- db-schema-drift-check com secrets configurados (ver E02 de
-- docs/plans/PLANO_DBA_CORRECOES_MELHORIAS_50_ETAPAS_2026-09-16.md), em
-- 5 rodadas sucessivas de CI (runs 35090629440 → 35093709593):
--
--   1. 20260601140841_*.sql        — `uuid ~ unknown`, sintaxe impossível.
--                                     CORRIGIDO (aposentado, nunca aplicado).
--   2. 20260601180000_*.sql        — `CREATE POLICY IF NOT EXISTS`, sintaxe
--                                     que não existe no PostgreSQL.
--                                     CORRIGIDO (reescrito com DO/EXCEPTION).
--   3. schema `analytics` ausente  — e mais 4 schemas de aplicação
--      (supplier_stricker, cf_recon, prod_audit, classification_audit)
--      sem NENHUMA migration de criação.
--                                     CORRIGIDO (bootstrap via pg_dump real).
--   4. `public.categories.bitrix_id` ausente — coluna de uma tabela core
--      sem nenhuma migration que a adicione, em NENHUM ponto da história.
--                                     NÃO CORRIGIDO — sinal de que a dívida
--                                     de DDL out-of-band vai além dos 5
--                                     schemas e pode se repetir em outras
--                                     tabelas `public`.
--
-- Decisão (2026-09-16): não perseguir mais gaps individuais via replay
-- completo — não há garantia de quantas camadas ainda existem, e cada
-- rodada custa um ciclo de CI. `SCHEMA_LIVE.sql` (dump direto do schema
-- vivo, sem depender de replay) passa a ser a fonte de verdade para
-- comparação estrutural a partir de hoje. A reconciliação histórica
-- completa (fazer o replay funcionar 100%) fica registrada como
-- E07/E08 do plano — best-effort, não bloqueante.
--
-- Este arquivo continua aqui, vazio de DDL, para que sua ausência não
-- seja confundida com "sem drift" por quem não ler este comentário.
