-- SCHEMA_DRIFT.sql — NÃO CALCULADO
-- Projeto: doufsxqlfjyuvxuezpln
-- Gerado em: 2026-09-22T14:24:59.026Z
-- Ledger divergente: 2499 pares, 474 somente locais, 2 somente remotos. Replay bloqueado.
-- Este arquivo não demonstra ausência de drift estrutural.
