CREATE INDEX idx_product_images_organization_id ON public.product_images(organization_id);
CREATE INDEX idx_products_sub_brand_id ON public.products(sub_brand_id);
CREATE INDEX idx_kit_enrichment_raw_* (2 indexes);
CREATE INDEX idx_kit_padronizacao_* (2 indexes);
CREATE INDEX idx_kit_variant_skus_color_id ON public.kit_component_variant_skus(item_color_id);
CREATE INDEX idx_product_kit_components_padronizacao;
CREATE INDEX idx_product_novelties_created_by;
CREATE INDEX idx_supplier_property_mappings_supplier;
CREATE INDEX idx_quotes_assigned_to;
CREATE INDEX idx_quotes_parent_quote_id;
CREATE INDEX idx_order_items_order_id;
CREATE INDEX idx_profiles_organization_id;
CREATE INDEX idx_generated_mockups_technique_id;
CREATE INDEX idx_mockup_txn_* (3 indexes);
CREATE INDEX idx_mockup_jobs_technique_id;
CREATE INDEX idx_product_faqs_category_id;
CREATE INDEX idx_product_group_members_group_id;
CREATE INDEX idx_markup_config_* (3 indexes);
CREATE INDEX idx_kit_comments_kit_id;
CREATE INDEX idx_kit_share_tokens_kit_id;
CREATE INDEX idx_kit_variants_kit_master;
